### ISSUE TITLE
Markdown Renderer not coping with yaml

### ISSUE THREAD

**Issue by marcus-j-davies** [node-red/flow-library#42]
Some instances of node red are being installed as plugins to Home Assistant.
it is therefore, going to cause a few work arounds for nodes to detail some yaml guidance (due to the HA restrictive platform).

I have noticed that yaml fails to Render correctly.

Here is the yaml Markdown.
```yaml
system_packages:
  - make
  - python3
  - g++
  - gcc
  - linux-headers
  - udev
npm_packages:
  - serialport
  - node-red-contrib-zwave-js
```

And here it is in the flows web page 🤷 

![image](https://user-images.githubusercontent.com/55892693/114055003-437a6100-9888-11eb-93f9-19735411af76.png)

I have noticed there is a PR for 2.0 of marked - would this bring the fix?
